program PascalCoinWalletClassic;

uses
  Vcl.Forms,
  UAccountKeyStorage in 'core\UAccountKeyStorage.pas',
  UAccounts in 'core\UAccounts.pas',
  UAES in 'core\UAES.pas',
  UBaseTypes in 'core\UBaseTypes.pas',
  UBlockChain in 'core\UBlockChain.pas',
  UChunk in 'core\UChunk.pas',
  UConst in 'core\UConst.pas',
  UCrypto in 'core\UCrypto.pas',
  UECIES in 'core\UECIES.pas',
  UFileStorage in 'core\UFileStorage.pas',
  ULog in 'core\ULog.pas',
  UNetProtocol in 'core\UNetProtocol.pas',
  UNode in 'core\UNode.pas',
  UOpenSSL in 'core\UOpenSSL.pas',
  UOpenSSLdef in 'core\UOpenSSLdef.pas',
  UOpTransaction in 'core\UOpTransaction.pas',
  URandomHash in 'core\URandomHash.pas',
  URPC in 'core\URPC.pas',
  USettings in 'core\USettings.pas',
  USha256 in 'core\USha256.pas',
  UTCPIP in 'core\UTCPIP.pas',
  UThread in 'core\UThread.pas',
  UTime in 'core\UTime.pas',
  UTxMultiOperation in 'core\UTxMultiOperation.pas',
  UWallet in 'core\UWallet.pas',
  UFRMAbout in 'gui-classic\UFRMAbout.pas' {FRMAbout},
  UFRMAccountInfo in 'gui-classic\UFRMAccountInfo.pas' {FRMAccountInfo},
  UFRMAccountSelect in 'gui-classic\UFRMAccountSelect.pas' {FRMAccountSelect},
  UFRMMemoText in 'gui-classic\UFRMMemoText.pas' {FRMMemoText},
  UFRMNewPrivateKeyType in 'gui-classic\UFRMNewPrivateKeyType.pas' {FRMNewPrivateKeyType},
  UFRMNodesIp in 'gui-classic\UFRMNodesIp.pas' {FRMNodesIp},
  UFRMOperation in 'gui-classic\UFRMOperation.pas' {FRMOperation},
  UFRMOperationsExplorer in 'gui-classic\UFRMOperationsExplorer.pas' {FRMOperationsExplorer},
  UFRMPascalCoinWalletConfig in 'gui-classic\UFRMPascalCoinWalletConfig.pas' {FRMPascalCoinWalletConfig},
  UFRMPayloadDecoder in 'gui-classic\UFRMPayloadDecoder.pas' {FRMPayloadDecoder},
  UFRMRandomOperations in 'gui-classic\UFRMRandomOperations.pas' {FRMRandomOperations},
  UFRMRPCCalls in 'gui-classic\UFRMRPCCalls.pas' {FRMRPCCalls},
  UFRMWallet in 'gui-classic\UFRMWallet.pas' {FRMWallet},
  UFRMWalletKeys in 'gui-classic\UFRMWalletKeys.pas' {FRMWalletKeys},
  HlpAdler32 in 'libraries\hashlib4pascal\HlpAdler32.pas',
  HlpAP in 'libraries\hashlib4pascal\HlpAP.pas',
  HlpBernstein in 'libraries\hashlib4pascal\HlpBernstein.pas',
  HlpBernstein1 in 'libraries\hashlib4pascal\HlpBernstein1.pas',
  HlpBitConverter in 'libraries\hashlib4pascal\HlpBitConverter.pas',
  HlpBits in 'libraries\hashlib4pascal\HlpBits.pas',
  HlpBKDR in 'libraries\hashlib4pascal\HlpBKDR.pas',
  HlpBlake2B in 'libraries\hashlib4pascal\HlpBlake2B.pas',
  HlpBlake2BConfig in 'libraries\hashlib4pascal\HlpBlake2BConfig.pas',
  HlpBlake2BIvBuilder in 'libraries\hashlib4pascal\HlpBlake2BIvBuilder.pas',
  HlpBlake2BTreeConfig in 'libraries\hashlib4pascal\HlpBlake2BTreeConfig.pas',
  HlpBlake2S in 'libraries\hashlib4pascal\HlpBlake2S.pas',
  HlpBlake2SConfig in 'libraries\hashlib4pascal\HlpBlake2SConfig.pas',
  HlpBlake2SIvBuilder in 'libraries\hashlib4pascal\HlpBlake2SIvBuilder.pas',
  HlpBlake2STreeConfig in 'libraries\hashlib4pascal\HlpBlake2STreeConfig.pas',
  HlpConverters in 'libraries\hashlib4pascal\HlpConverters.pas',
  HlpCRC in 'libraries\hashlib4pascal\HlpCRC.pas',
  HlpCRC16 in 'libraries\hashlib4pascal\HlpCRC16.pas',
  HlpCRC32 in 'libraries\hashlib4pascal\HlpCRC32.pas',
  HlpCRC64 in 'libraries\hashlib4pascal\HlpCRC64.pas',
  HlpDEK in 'libraries\hashlib4pascal\HlpDEK.pas',
  HlpDJB in 'libraries\hashlib4pascal\HlpDJB.pas',
  HlpELF in 'libraries\hashlib4pascal\HlpELF.pas',
  HlpFNV in 'libraries\hashlib4pascal\HlpFNV.pas',
  HlpFNV1a in 'libraries\hashlib4pascal\HlpFNV1a.pas',
  HlpFNV1a64 in 'libraries\hashlib4pascal\HlpFNV1a64.pas',
  HlpFNV64 in 'libraries\hashlib4pascal\HlpFNV64.pas',
  HlpGost in 'libraries\hashlib4pascal\HlpGost.pas',
  HlpGOST3411_2012 in 'libraries\hashlib4pascal\HlpGOST3411_2012.pas',
  HlpGrindahl256 in 'libraries\hashlib4pascal\HlpGrindahl256.pas',
  HlpGrindahl512 in 'libraries\hashlib4pascal\HlpGrindahl512.pas',
  HlpHAS160 in 'libraries\hashlib4pascal\HlpHAS160.pas',
  HlpHash in 'libraries\hashlib4pascal\HlpHash.pas',
  HlpHashBuffer in 'libraries\hashlib4pascal\HlpHashBuffer.pas',
  HlpHashCryptoNotBuildIn in 'libraries\hashlib4pascal\HlpHashCryptoNotBuildIn.pas',
  HlpHashFactory in 'libraries\hashlib4pascal\HlpHashFactory.pas',
  HlpHashLibTypes in 'libraries\hashlib4pascal\HlpHashLibTypes.pas',
  HlpHashResult in 'libraries\hashlib4pascal\HlpHashResult.pas',
  HlpHashRounds in 'libraries\hashlib4pascal\HlpHashRounds.pas',
  HlpHashSize in 'libraries\hashlib4pascal\HlpHashSize.pas',
  HlpHaval in 'libraries\hashlib4pascal\HlpHaval.pas',
  HlpHMACNotBuildInAdapter in 'libraries\hashlib4pascal\HlpHMACNotBuildInAdapter.pas',
  HlpIBlake2BConfig in 'libraries\hashlib4pascal\HlpIBlake2BConfig.pas',
  HlpIBlake2BTreeConfig in 'libraries\hashlib4pascal\HlpIBlake2BTreeConfig.pas',
  HlpIBlake2SConfig in 'libraries\hashlib4pascal\HlpIBlake2SConfig.pas',
  HlpIBlake2STreeConfig in 'libraries\hashlib4pascal\HlpIBlake2STreeConfig.pas',
  HlpICRC in 'libraries\hashlib4pascal\HlpICRC.pas',
  HlpIHash in 'libraries\hashlib4pascal\HlpIHash.pas',
  HlpIHashInfo in 'libraries\hashlib4pascal\HlpIHashInfo.pas',
  HlpIHashResult in 'libraries\hashlib4pascal\HlpIHashResult.pas',
  HlpIKDF in 'libraries\hashlib4pascal\HlpIKDF.pas',
  HlpJenkins3 in 'libraries\hashlib4pascal\HlpJenkins3.pas',
  HlpJS in 'libraries\hashlib4pascal\HlpJS.pas',
  HlpKDF in 'libraries\hashlib4pascal\HlpKDF.pas',
  HlpMD2 in 'libraries\hashlib4pascal\HlpMD2.pas',
  HlpMD4 in 'libraries\hashlib4pascal\HlpMD4.pas',
  HlpMD5 in 'libraries\hashlib4pascal\HlpMD5.pas',
  HlpMDBase in 'libraries\hashlib4pascal\HlpMDBase.pas',
  HlpMultipleTransformNonBlock in 'libraries\hashlib4pascal\HlpMultipleTransformNonBlock.pas',
  HlpMurmur2 in 'libraries\hashlib4pascal\HlpMurmur2.pas',
  HlpMurmur2_64 in 'libraries\hashlib4pascal\HlpMurmur2_64.pas',
  HlpMurmurHash3_x64_128 in 'libraries\hashlib4pascal\HlpMurmurHash3_x64_128.pas',
  HlpMurmurHash3_x86_32 in 'libraries\hashlib4pascal\HlpMurmurHash3_x86_32.pas',
  HlpMurmurHash3_x86_128 in 'libraries\hashlib4pascal\HlpMurmurHash3_x86_128.pas',
  HlpNullable in 'libraries\hashlib4pascal\HlpNullable.pas',
  HlpNullDigest in 'libraries\hashlib4pascal\HlpNullDigest.pas',
  HlpOneAtTime in 'libraries\hashlib4pascal\HlpOneAtTime.pas',
  HlpPanama in 'libraries\hashlib4pascal\HlpPanama.pas',
  HlpPBKDF2_HMACNotBuildInAdapter in 'libraries\hashlib4pascal\HlpPBKDF2_HMACNotBuildInAdapter.pas',
  HlpPJW in 'libraries\hashlib4pascal\HlpPJW.pas',
  HlpRadioGatun32 in 'libraries\hashlib4pascal\HlpRadioGatun32.pas',
  HlpRadioGatun64 in 'libraries\hashlib4pascal\HlpRadioGatun64.pas',
  HlpRIPEMD in 'libraries\hashlib4pascal\HlpRIPEMD.pas',
  HlpRIPEMD128 in 'libraries\hashlib4pascal\HlpRIPEMD128.pas',
  HlpRIPEMD160 in 'libraries\hashlib4pascal\HlpRIPEMD160.pas',
  HlpRIPEMD256 in 'libraries\hashlib4pascal\HlpRIPEMD256.pas',
  HlpRIPEMD320 in 'libraries\hashlib4pascal\HlpRIPEMD320.pas',
  HlpRotating in 'libraries\hashlib4pascal\HlpRotating.pas',
  HlpRS in 'libraries\hashlib4pascal\HlpRS.pas',
  HlpSDBM in 'libraries\hashlib4pascal\HlpSDBM.pas',
  HlpSHA0 in 'libraries\hashlib4pascal\HlpSHA0.pas',
  HlpSHA1 in 'libraries\hashlib4pascal\HlpSHA1.pas',
  HlpSHA2_224 in 'libraries\hashlib4pascal\HlpSHA2_224.pas',
  HlpSHA2_256 in 'libraries\hashlib4pascal\HlpSHA2_256.pas',
  HlpSHA2_256Base in 'libraries\hashlib4pascal\HlpSHA2_256Base.pas',
  HlpSHA2_384 in 'libraries\hashlib4pascal\HlpSHA2_384.pas',
  HlpSHA2_512 in 'libraries\hashlib4pascal\HlpSHA2_512.pas',
  HlpSHA2_512_224 in 'libraries\hashlib4pascal\HlpSHA2_512_224.pas',
  HlpSHA2_512_256 in 'libraries\hashlib4pascal\HlpSHA2_512_256.pas',
  HlpSHA2_512Base in 'libraries\hashlib4pascal\HlpSHA2_512Base.pas',
  HlpSHA3 in 'libraries\hashlib4pascal\HlpSHA3.pas',
  HlpShiftAndXor in 'libraries\hashlib4pascal\HlpShiftAndXor.pas',
  HlpSipHash in 'libraries\hashlib4pascal\HlpSipHash.pas',
  HlpSnefru in 'libraries\hashlib4pascal\HlpSnefru.pas',
  HlpSuperFast in 'libraries\hashlib4pascal\HlpSuperFast.pas',
  HlpTiger in 'libraries\hashlib4pascal\HlpTiger.pas',
  HlpTiger2 in 'libraries\hashlib4pascal\HlpTiger2.pas',
  HlpWhirlPool in 'libraries\hashlib4pascal\HlpWhirlPool.pas',
  HlpXXHash32 in 'libraries\hashlib4pascal\HlpXXHash32.pas',
  HlpXXHash64 in 'libraries\hashlib4pascal\HlpXXHash64.pas',
  UCommon in 'libraries\sphere10\UCommon.pas',
  UMemory in 'libraries\sphere10\UMemory.pas',
  blcksock in 'libraries\synapse\blcksock.pas',
  synacode in 'libraries\synapse\synacode.pas',
  synafpc in 'libraries\synapse\synafpc.pas',
  synaip in 'libraries\synapse\synaip.pas',
  synautil in 'libraries\synapse\synautil.pas',
  httpsend in 'libraries\synapse\httpsend.pas',
  synsock in 'libraries\synapse\synsock.pas',
  UAppParams in 'libraries\pascalcoin\UAppParams.pas',
  UFolderHelper in 'libraries\pascalcoin\UFolderHelper.pas',
  UJSONFunctions in 'libraries\pascalcoin\UJSONFunctions.pas',
  UGridUtils in 'gui-classic\UGridUtils.pas',
  UPoolMining in 'core\UPoolMining.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TFRMWallet, FRMWallet);
  Application.Run;
end.
